/**
 * Compiles src/styles.css into a TS string module so the component can inject
 * its own stylesheet — consumers should not have to import CSS by hand.
 *
 * Runs as part of `npm run build`; the output is committed so `tsc` and the
 * demo work straight from a clone.
 */
import { readFileSync, writeFileSync } from "node:fs";

const css = readFileSync("src/styles.css", "utf8")
  .replace(/\/\*[\s\S]*?\*\//g, "")
  .replace(/\s*\n\s*/g, "\n")
  .replace(/\n{2,}/g, "\n")
  .trim();

const out = `/**
 * GENERATED by scripts/gen-css.mjs from src/styles.css — do not edit by hand.
 */
export const STYLES = ${JSON.stringify(css)};
`;

writeFileSync("src/styles.gen.ts", out);
console.log(`wrote src/styles.gen.ts — ${(Buffer.byteLength(out) / 1024).toFixed(1)} kB`);
