/**
 * Vendors the SVG flags for every country used by the dataset into
 * `src/flags.data.ts`, so the published package needs no runtime dependency and
 * no network to draw a flag.
 *
 * Source artwork: `country-flag-icons` (MIT) — a devDependency, never shipped.
 * Run with `npm run gen:flags` after changing the currency dataset.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const SRC_DIR = "node_modules/country-flag-icons/3x2";
const OUT = "src/flags.data.ts";

const dataset = readFileSync("src/currencies.ts", "utf8");
const countries = [...new Set([...dataset.matchAll(/country: "([A-Z]{2})"/g)].map((m) => m[1]))].sort();

const minify = (svg) =>
  svg
    .replace(/<\?xml[^>]*\?>/g, "")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/>\s+</g, "><")
    .replace(/\s{2,}/g, " ")
    // Single-quoted attributes survive a double-quoted JS string unescaped.
    .replace(/="([^"]*)"/g, "='$1'")
    .trim();

const missing = [];
const rows = [];
for (const country of countries) {
  const path = `${SRC_DIR}/${country}.svg`;
  if (!existsSync(path)) {
    missing.push(country);
    continue;
  }
  rows.push(`  ${country}: "${minify(readFileSync(path, "utf8"))}",`);
}

if (missing.length) {
  console.warn(`no SVG for: ${missing.join(", ")} — those fall back to the emoji flag`);
}

const file = `/**
 * GENERATED by scripts/gen-flags.mjs — do not edit by hand.
 *
 * ${rows.length} flags, one inline SVG string per ISO 3166-1 alpha-2 code.
 * Artwork from country-flag-icons (MIT, https://github.com/catamphetamine/country-flag-icons),
 * which is a build-time devDependency only. Countries outside this map fall
 * back to the Unicode emoji flag.
 */
export const FLAG_SVGS: Record<string, string> = {
${rows.join("\n")}
};
`;

writeFileSync(OUT, file);
const kb = (Buffer.byteLength(file) / 1024).toFixed(1);
console.log(`wrote ${OUT} — ${rows.length} flags, ${kb} kB`);
