import type { Currency } from "./types";

/**
 * 141 widely-used world currencies, sorted by ISO 4217 code.
 * Only `code`, `name`, `symbol` and `country` are stored — the flag emoji is
 * derived at runtime from `country` via `toFlag`, so no glyphs live in here.
 * Multi-country currencies use one representative country (EUR -> "EU").
 */
export const currencies: Currency[] = [
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", country: "AE" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", country: "AF" },
  { code: "ALL", name: "Albanian Lek", symbol: "L", country: "AL" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", country: "AM" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", country: "AO" },
  { code: "ARS", name: "Argentine Peso", symbol: "$", country: "AR" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", country: "AU" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", country: "AZ" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM", country: "BA" },
  { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$", country: "BB" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", country: "BD" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", country: "BG" },
  { code: "BHD", name: "Bahraini Dinar", symbol: "د.ب", country: "BH" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu", country: "BI" },
  { code: "BND", name: "Brunei Dollar", symbol: "B$", country: "BN" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs", country: "BO" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", country: "BR" },
  { code: "BSD", name: "Bahamian Dollar", symbol: "B$", country: "BS" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", country: "BT" },
  { code: "BWP", name: "Botswanan Pula", symbol: "P", country: "BW" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", country: "BY" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", country: "BZ" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", country: "CA" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC", country: "CD" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", country: "CH" },
  { code: "CLP", name: "Chilean Peso", symbol: "$", country: "CL" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", country: "CN" },
  { code: "COP", name: "Colombian Peso", symbol: "$", country: "CO" },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡", country: "CR" },
  { code: "CUP", name: "Cuban Peso", symbol: "$", country: "CU" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$", country: "CV" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", country: "CZ" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", country: "DJ" },
  { code: "DKK", name: "Danish Krone", symbol: "kr", country: "DK" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", country: "DO" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", country: "DZ" },
  { code: "EGP", name: "Egyptian Pound", symbol: "£", country: "EG" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", country: "ER" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", country: "ET" },
  { code: "EUR", name: "Euro", symbol: "€", country: "EU" },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", country: "FJ" },
  { code: "GBP", name: "British Pound", symbol: "£", country: "GB" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", country: "GE" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", country: "GH" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", country: "GM" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", country: "GN" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", country: "GT" },
  { code: "GYD", name: "Guyanaese Dollar", symbol: "G$", country: "GY" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", country: "HK" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", country: "HN" },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", country: "HT" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", country: "HU" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", country: "ID" },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪", country: "IL" },
  { code: "INR", name: "Indian Rupee", symbol: "₹", country: "IN" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", country: "IQ" },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", country: "IR" },
  { code: "ISK", name: "Icelandic Króna", symbol: "kr", country: "IS" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", country: "JM" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", country: "JO" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", country: "JP" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", country: "KE" },
  { code: "KGS", name: "Kyrgystani Som", symbol: "с", country: "KG" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", country: "KH" },
  { code: "KMF", name: "Comorian Franc", symbol: "CF", country: "KM" },
  { code: "KRW", name: "South Korean Won", symbol: "₩", country: "KR" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", country: "KW" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", country: "KZ" },
  { code: "LAK", name: "Laotian Kip", symbol: "₭", country: "LA" },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", country: "LB" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨", country: "LK" },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$", country: "LR" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", country: "LS" },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", country: "LY" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", country: "MA" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", country: "MD" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", country: "MG" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", country: "MK" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", country: "MM" },
  { code: "MNT", name: "Mongolian Tugrik", symbol: "₮", country: "MN" },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$", country: "MO" },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", country: "MR" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨", country: "MU" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", country: "MV" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", country: "MW" },
  { code: "MXN", name: "Mexican Peso", symbol: "$", country: "MX" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", country: "MY" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT", country: "MZ" },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$", country: "NA" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", country: "NG" },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", country: "NI" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", country: "NO" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", country: "NP" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", country: "NZ" },
  { code: "OMR", name: "Omani Rial", symbol: "ر.ع.", country: "OM" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", country: "PA" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/", country: "PE" },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", country: "PG" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", country: "PH" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", country: "PK" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", country: "PL" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "₲", country: "PY" },
  { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق", country: "QA" },
  { code: "RON", name: "Romanian Leu", symbol: "lei", country: "RO" },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин.", country: "RS" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", country: "RU" },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw", country: "RW" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼", country: "SA" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨", country: "SC" },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س", country: "SD" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", country: "SE" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", country: "SG" },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le", country: "SL" },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh", country: "SO" },
  { code: "SRD", name: "Surinamese Dollar", symbol: "$", country: "SR" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "£", country: "SS" },
  { code: "SYP", name: "Syrian Pound", symbol: "£", country: "SY" },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "E", country: "SZ" },
  { code: "THB", name: "Thai Baht", symbol: "฿", country: "TH" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", country: "TJ" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "m", country: "TM" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", country: "TN" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", country: "TR" },
  { code: "TTD", name: "Trinidad & Tobago Dollar", symbol: "TT$", country: "TT" },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", country: "TW" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", country: "TZ" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", country: "UA" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh", country: "UG" },
  { code: "USD", name: "US Dollar", symbol: "$", country: "US" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", country: "UY" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "soʻm", country: "UZ" },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "Bs.", country: "VE" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", country: "VN" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA", country: "CM" },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$", country: "AG" },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA", country: "SN" },
  { code: "XPF", name: "CFP Franc", symbol: "₣", country: "PF" },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", country: "YE" },
  { code: "ZAR", name: "South African Rand", symbol: "R", country: "ZA" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", country: "ZM" },
  { code: "ZWG", name: "Zimbabwe Gold", symbol: "ZiG", country: "ZW" },
];
